### ISSUE TITLE
An unexpected error happened - Error: Minified React error #301

### ISSUE THREAD

**Issue by patchie** [grafana/grafana-llm-app#221]
Installed last version of Grafana(10.3.3)
Installed last version of LLM plugin(0.6.0)
Enabled "dashgpt" Feature.
Configured the plugin with Azure OpenAI:
![image](https://github.com/grafana/grafana-llm-app/assets/1792727/cc5404a8-8945-4169-bc95-f350b7e21c79)

How to recreate the problem:
1. Open a dashboard
2. Go to dashboard settings
3. Press "Auto Generate"
![image](https://github.com/grafana/grafana-llm-app/assets/1792727/4e2ba95d-c1f4-40ac-9c1b-82b7cf25bccc)
4. An unexpected error happened. Screenshot below:
![image](https://github.com/grafana/grafana-llm-app/assets/1792727/008b4d4b-eed6-40a7-a1a3-f89ea80bc36e)

Full error message below:
```
An unexpected error happened
Details
Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at Q (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:1976:7196)
    at m (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:1984:69)
    at div
    at div
    at o (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:211:47906)
    at g (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:211:48262)
    at div
    at http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:192:134859
    at div
    at http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:211:45043
    at div
    at div
    at div
    at div
    at div
    at X (http://hostname:3000/public/build/1663.190becda783f60342f79.js:124:36505)
    at m (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:192:29691)
    at div
    at W (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:404:21349)
    at Jt (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:1966:1003)
    at Vt (http://hostname:3000/public/build/1663.190becda783f60342f79.js:183:66201)
    at gr (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:1974:3599)
    at vn (http://hostname:3000/public/build/DashboardPageProxy.dbec33b5fdad6d16d25e.js:407:474)
    at DashboardPage
    at Vt (http://hostname:3000/public/build/1663.190becda783f60342f79.js:183:66201)
    at So (http://hostname:3000/public/build/DashboardPageProxy.dbec33b5fdad6d16d25e.js:407:6597)
    at Suspense
    at o (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:192:118866)
    at bo (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:349:10002)
    at be (http://hostname:3000/public/build/1663.190becda783f60342f79.js:228:23522)
    at uo (http://hostname:3000/public/build/1663.190becda783f60342f79.js:209:4728)
    at Jn (http://hostname:3000/public/build/1663.190becda783f60342f79.js:209:10219)
    at el (http://hostname:3000/public/build/1663.190becda783f60342f79.js:228:11773)
    at be (http://hostname:3000/public/build/1663.190becda783f60342f79.js:228:25717)
    at div
    at div
    at main
    at div
    at Ji (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:349:2441)
    at uo (http://hostname:3000/public/build/1663.190becda783f60342f79.js:209:4728)
    at Jn (http://hostname:3000/public/build/1663.190becda783f60342f79.js:209:10219)
    at Cn (http://hostname:3000/public/build/1663.190becda783f60342f79.js:209:9608)
    at Dl (http://hostname:3000/public/build/1663.190becda783f60342f79.js:228:12072)
    at be (http://hostname:3000/public/build/1663.190becda783f60342f79.js:228:19694)
    at div
    at i (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:212:13890)
    at d (http://hostname:3000/public/build/1663.190becda783f60342f79.js:41:13951)
    at p (http://hostname:3000/public/build/1663.190becda783f60342f79.js:683:233964)
    at d (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:700:21358)
    at o (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:192:118866)
    at g (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:192:119375)
    at Ae (http://hostname:3000/public/build/1663.190becda783f60342f79.js:187:530)
    at Br (http://hostname:3000/public/build/8291.c757e598a21c790323c9.js:360:127)
```

**Comment by csmarchbanks** [comment]
Thank you for the report! @SandersAaronD could you investigate this? I am not sure if the error is from the Dashboard code or our plugin. I think it might be the dashboard code though?

**Comment by SandersAaronD** [comment]
This is almost certainly the dashgpt code, Grafana versions after 10.2.0 have produced dependency and build problems for them. I will make sure this gets linked to efforts around that so that we don't consider them fixed until this is fixed.

**Comment by bossjie** [comment]
I met the same issue.  thanks @SandersAaronD

**Comment by Kurtoid** [comment]
I have this too - 11.6 with latest (0.17) LLM plugin and the generate buttons are missing

**Comment by Kurtoid** [comment]
Somehow in v11.6.1 (ae23ead4d9) with 0.17.0, the generate buttons appeared again, and seem to be functional. Not sure what changed

**Comment by KarolQuilachamin** [comment]
Hi i have the same bug, and the integration its ok

Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
